default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auth_app_development
  username: auth_app
  password: "root"
  host: localhost
  port: 5432
  schema_search_path: myapp,sharedapp,public
  min_messages: notice

test:
  <<: *default
  database: auth_app_test
  username: auth_app
  password: "root"
  host: localhost
  port: 5432

production:
  <<: *default
  database: auth_app_production
  username: auth_app
  password: "root"
  host: localhost
  port: 5432